-- 코드를 작성해주세요
WITH rare_id as (
    SELECT ITEM_ID
    FROM ITEM_INFO
    WHERE RARITY = 'RARE'
)

SELECT DISTINCT ITEM_INFO.ITEM_ID, ITEM_INFO.ITEM_NAME, ITEM_INFO.RARITY
FROM ITEM_INFO, rare_id, ITEM_TREE
WHERE ITEM_TREE.PARENT_ITEM_ID = rare_id.ITEM_ID && ITEM_INFO.ITEM_ID = ITEM_TREE.ITEM_ID
ORDER BY ITEM_ID DESC;