-- 코드를 작성해주세요
WITH pc as (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME = 'Python' || NAME = 'C#'
)

SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS, pc
WHERE pc.CODE & DEVELOPERS.SKILL_CODE > 0
ORDER BY ID;