-- 코드를 작성해주세요
WITH fi_name as (
    SELECT FISH_TYPE
    FROM FISH_NAME_INFO
    WHERE FISH_NAME = 'BASS' || FISH_NAME = 'SNAPPER'
)

SELECT COUNT(FISH_INFO.FISH_TYPE) as FISH_COUNT
FROM FISH_INFO, fi_name
WHERE FISH_INFO.FISH_TYPE = fi_name.FISH_TYPE;