-- 코드를 입력하세요
WITH fr_flavor AS (
    SELECT FLAVOR
    FROM ICECREAM_INFO
    WHERE INGREDIENT_TYPE = 'fruit_based'
)

SELECT FIRST_HALF.FLAVOR
FROM FIRST_HALF, fr_flavor
WHERE TOTAL_ORDER >=3000 && FIRST_HALF.FLAVOR = fr_flavor.FLAVOR
ORDER BY TOTAL_ORDER DESC;